### ISSUE TITLE
Add scrollbar to metrics menu

### ISSUE THREAD

**Issue by EranOfer** [Recognos/Metrics.NET.FlotVisualization#1]
Unable to reach some of the menu item - (when the list is too long).

Before

![image](https://cloud.githubusercontent.com/assets/13414515/25850789/44bd578a-34cc-11e7-88c6-f4c963ee50e1.png)

After

![image](https://cloud.githubusercontent.com/assets/13414515/25850781/37851026-34cc-11e7-985e-cb839a1788d8.png)

```
       $(document).ready(()=>
         {
             $( window ).on("load", function() {
                 $('.dropdown-menu').css('max-height', window.innerHeight - 80);
             });
 
             $( window ).on("resize", function() {
                 $('.dropdown-menu').css('max-height', window.innerHeight - 80);
             });
         });
```

```
.dropdown-menu {
...
...
//Add
    overflow: auto
}

````

**Comment by PaulParau** [comment]
Hi,

Your fix gets removed by the build process, so it will not work in the release (minified/combined) version of the app.

You can observe this yourself by running `grunt serve:dist`.

Please fix this and make another pull request.

**Comment by EranOfer** [comment]
I created a new marge request:
 https://github.com/Recognos/Metrics.NET.FlotVisualization/pull/3

You can run  ```grunt serve:dist -force ```.
I verified it works ,you can minimize the screen and look on the Health status it should have a scroll bar.

**Comment by PaulParau** [comment]
Awesome, thanks!

I've updated the visualization app in version 0.5.3-pre, and it seems to be working correctly.

**Comment by EranOfer** [comment]
Hi,
I started using and It working great.
Can you create a release version ?
thanks.

**Comment by PaulParau** [comment]
@EranOfer i've just pushed release version v0.5.3
